### ISSUE TITLE
Get Sankey (flow) diagram working

### ISSUE THREAD

**Issue by LeaderOne** [codefortulsa/openbudgettulsa#7]
Help get the d3 code working for the Sankey diagram.  This is a major deliverable for the mayor.

**Comment by jdungan** [comment]
I've reviewed the sankey doc and example.  Where is the Tulsa data?

**Comment by LeaderOne** [comment]
It should be there when you pull.  /_src/data/tulsa/c4tul*

**Comment by jdungan** [comment]
Closed by #8
